apiVersion: v1
kind: ConfigMap
metadata:
  name: test-connection-config
  namespace: stocksblitz
data:
  ENV: "prod"
  USE_MOCKS: "false"
  REDIS_HOST: "redis-cluster.stocksblitz.svc.cluster.local"
  REDIS_PORT: "6379"
  POSTGRES_USER: "tradmin"
  POSTGRES_PASSWORD: "tradpass"
  POSTGRES_HOST: "timescaledb.stocksblitz.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "tradingdb"
  MONGO_URI: "mongodb://mongo.stocksblitz.svc.cluster.local:27017/"
  RABBITMQ_URI: "amqp://guest:guest@rabbitmq.stocksblitz.svc.cluster.local/"
