name: Dev - Build and Deploy to KIND

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!infra/**"

jobs:
  build-and-deploy-dev:
    name: Build and Deploy Dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 📦 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔥 Build Docker Image for Development
        run: |
          docker build -t test_connection_service:dev -f docker/Dockerfile .

      - name: 📥 Download redeploy_service.sh
        run: |
          curl -o redeploy_service.sh https://raw.githubusercontent.com/raghurammutya/infra/main/scripts/redeploy_service.sh
          chmod +x redeploy_service.sh

      - name: ⚡ Load Image into KIND
        run: |
          kind load docker-image test_connection_service:dev

      - name: 🚀 Redeploy on KIND
        run: |
          ./redeploy_service.sh test-connection-service
