name: Prod - Build and Push to GHCR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push-prod:
    name: Build and Push Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 📦 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔥 Build and Push Docker Image to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u raghurammutya --password-stdin
          docker buildx build --push --tag ghcr.io/raghurammutya/test_connection_service:latest -f docker/Dockerfile .
